workspace:
  base: /pipeline
  path: src

pipeline:
  build:
    image: redis
    commands:
      - pwd
      - find ./
      - redis-cli -h redis ping
      - redis-cli -h redis set FOO bar
      - redis-cli -h redis get FOO

services:
  redis:
    image: redis
